### ISSUE TITLE
Text should be bigger 

### ISSUE THREAD

**Issue by vladkaryakin** [Jka4/AirBnB#6]
http://joxi.ru/DmBwMGocJlRN52 - твоя страничка
http://joxi.ru/J2bkKGpC0bP0EA - макет

**Comment by Jka4** [comment]
Хм, такое чувство что что-то не прогружает 
Т.к. у меня отображается совсем по другому
![image](https://user-images.githubusercontent.com/45815145/60684429-605d5580-9ea6-11e9-9cdb-0f8d98fe5e8d.png)
